name: Test
on:
  pull_request:
  push:
    branches:
      - primary

jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm ci
      - run: npm run ci
  integrationTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm ci
      - run: npm run build
      - uses: ./
        id: assigned
        with:
          query: 'label:for-testing'
          token: ${{ github.token }}
      - run: exit 1
        name: "Fail unless steps.assigned.outputs.last == 'lee-dohm'"
        if: steps.assigned.outputs.last != 'lee-dohm'
